### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by IamCage** [zombieFox/hexagonTab#13]
hello mate, first thank you for your awesome project.
can you write detailed install guide or make it this project on docker?
thank you in advance

**Comment by zombieFox** [comment]
Hi, glad you like the project. Sorry I don't know how to make hexagonTab work with Docker. What are you aiming to achieve or what problem is Docker solving for you?

I'm also reluctant to add something to the project that I don't understand and can't provide support for. So this project is just a Chrome and Firefox extension.

**Comment by IamCage** [comment]
ahhh okay. the bottom of your code, you write to install with "npm" command, but what is first step? wget -O your code or?

**Comment by zombieFox** [comment]
Oh, I see! You should clone the repo locally using [Git](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository-from-github/cloning-a-repository). Then run `npm i` in the cloned repo folder to install dependencies. Then `npm start` to run it.

**Comment by IamCage** [comment]
thank you, thats i need :)
