### ISSUE TITLE
Having HexagonTab load as the homepage as well? 

### ISSUE THREAD

**Issue by dreadbalaur** [zombieFox/hexagonTab#18]
I almost never use Firefox Home. The occasions where it pops up in a new window are quite jarring to the rest of my Firefox theme. Is it possible to load Firefox with HexagonTab as the homepage?

**Comment by zombieFox** [comment]
This is a Firefox issue. For a workaround please see the wiki page on [Setting hexagonTab as your Firefox homepage](https://github.com/zombieFox/hexagonTab/wiki/Setting-hexagonTab-as-your-Firefox-homepage)
